[package]
authors = ["Sebastian Menski <sebastian@menski.org>"]
name = "unterflow-protocol"
version = "0.2.0"

[dependencies]
byteorder = "1.0.0"
error-chain = "0.10.0"
rmpv = "0.4.0"

[dependencies.unterflow-derive]
optional = false
path = "../unterflow-derive/"
