[package]
authors = ["Sebastian Menski <sebastian@menski.org>"]
name = "unterflow-dump"
version = "0.2.0"

[dependencies]
clap = "2.24.2"
error-chain = "0.10.0"
log = "0.3.8"
loggerv = "0.3.0"
pnet = "0.17.1"

[dependencies.unterflow-protocol]
optional = false
path = "../unterflow-protocol/"
